networks:
  mgmt:
    driver_opts:
      com.docker.network.container_iface_prefix: xr-12
    ipam:
      config:
      - subnet: 172.30.0.0/24
  xrd-1-gi0-xrd-3-gi2:
    driver_opts:
      com.docker.network.container_iface_prefix: xr-0
      com.docker.network.driver.mtu: 9000
    internal: true
    name: xrd-1-gi0-xrd-3-gi2
  xrd-1-gi1-xrd-5-gi2:
    driver_opts:
      com.docker.network.container_iface_prefix: xr-1
      com.docker.network.driver.mtu: 9000
    internal: true
    name: xrd-1-gi1-xrd-5-gi2
  xrd-2-gi0-xrd-4-gi2:
    driver_opts:
      com.docker.network.container_iface_prefix: xr-2
      com.docker.network.driver.mtu: 9000
    internal: true
    name: xrd-2-gi0-xrd-4-gi2
  xrd-2-gi1-xrd-6-gi2:
    driver_opts:
      com.docker.network.container_iface_prefix: xr-3
      com.docker.network.driver.mtu: 9000
    internal: true
    name: xrd-2-gi1-xrd-6-gi2
  xrd-3-gi0-xrd-4-gi0:
    driver_opts:
      com.docker.network.container_iface_prefix: xr-4
      com.docker.network.driver.mtu: 9000
    internal: true
    name: xrd-3-gi0-xrd-4-gi0
  xrd-3-gi1-xrd-5-gi1:
    driver_opts:
      com.docker.network.container_iface_prefix: xr-5
      com.docker.network.driver.mtu: 9000
    internal: true
    name: xrd-3-gi1-xrd-5-gi1
  xrd-3-gi3-xrd-7-gi0:
    driver_opts:
      com.docker.network.container_iface_prefix: xr-8
      com.docker.network.driver.mtu: 9000
    internal: true
    name: xrd-3-gi3-xrd-7-gi0
  xrd-4-gi1-xrd-6-gi1:
    driver_opts:
      com.docker.network.container_iface_prefix: xr-6
      com.docker.network.driver.mtu: 9000
    internal: true
    name: xrd-4-gi1-xrd-6-gi1
  xrd-4-gi3-xrd-7-gi1:
    driver_opts:
      com.docker.network.container_iface_prefix: xr-9
      com.docker.network.driver.mtu: 9000
    internal: true
    name: xrd-4-gi3-xrd-7-gi1
  xrd-5-gi0-xrd-6-gi0:
    driver_opts:
      com.docker.network.container_iface_prefix: xr-7
      com.docker.network.driver.mtu: 9000
    internal: true
    name: xrd-5-gi0-xrd-6-gi0
  xrd-5-gi3-xrd-8-gi0:
    driver_opts:
      com.docker.network.container_iface_prefix: xr-10
      com.docker.network.driver.mtu: 9000
    internal: true
    name: xrd-5-gi3-xrd-8-gi0
  xrd-6-gi3-xrd-8-gi1:
    driver_opts:
      com.docker.network.container_iface_prefix: xr-11
      com.docker.network.driver.mtu: 9000
    internal: true
    name: xrd-6-gi3-xrd-8-gi1
services:
  xrd-1:
    cap_add:
    - CHOWN
    - DAC_OVERRIDE
    - FSETID
    - FOWNER
    - MKNOD
    - NET_RAW
    - SETGID
    - SETUID
    - SETFCAP
    - SETPCAP
    - NET_BIND_SERVICE
    - SYS_CHROOT
    - KILL
    - AUDIT_WRITE
    - SYS_NICE
    - SYS_ADMIN
    - SYS_RESOURCE
    - NET_ADMIN
    - SYS_PTRACE
    - IPC_LOCK
    cap_drop:
    - all
    container_name: xrd-1
    devices:
    - /dev/fuse
    - /dev/net/tun
    environment:
      XR_EVERY_BOOT_CONFIG: /etc/xrd/startup.cfg
      XR_INTERFACES: linux:xr-00,xr_name=Gi0/0/0/0;linux:xr-10,xr_name=Gi0/0/0/1
      XR_MGMT_INTERFACES: linux:xr-120,xr_name=Mg0/RP0/CPU0/0,chksum
    image: ios-xr/xrd-control-plane:25.1.1
    networks:
      mgmt: null
      xrd-1-gi0-xrd-3-gi2: null
      xrd-1-gi1-xrd-5-gi2: null
    pids_limit: -1
    security_opt:
    - apparmor=unconfined
    - label=disable
    stdin_open: true
    tty: true
    volumes:
    - source: ./xrd-1-startup.cfg
      target: /etc/xrd/startup.cfg
      type: bind
    - xrd-1:/xr-storage/
  xrd-2:
    cap_add:
    - CHOWN
    - DAC_OVERRIDE
    - FSETID
    - FOWNER
    - MKNOD
    - NET_RAW
    - SETGID
    - SETUID
    - SETFCAP
    - SETPCAP
    - NET_BIND_SERVICE
    - SYS_CHROOT
    - KILL
    - AUDIT_WRITE
    - SYS_NICE
    - SYS_ADMIN
    - SYS_RESOURCE
    - NET_ADMIN
    - SYS_PTRACE
    - IPC_LOCK
    cap_drop:
    - all
    container_name: xrd-2
    devices:
    - /dev/fuse
    - /dev/net/tun
    environment:
      XR_EVERY_BOOT_CONFIG: /etc/xrd/startup.cfg
      XR_INTERFACES: linux:xr-20,xr_name=Gi0/0/0/0;linux:xr-30,xr_name=Gi0/0/0/1
      XR_MGMT_INTERFACES: linux:xr-120,xr_name=Mg0/RP0/CPU0/0,chksum
    image: ios-xr/xrd-control-plane:25.1.1
    networks:
      mgmt: null
      xrd-2-gi0-xrd-4-gi2: null
      xrd-2-gi1-xrd-6-gi2: null
    pids_limit: -1
    security_opt:
    - apparmor=unconfined
    - label=disable
    stdin_open: true
    tty: true
    volumes:
    - source: ./xrd-2-startup.cfg
      target: /etc/xrd/startup.cfg
      type: bind
    - xrd-2:/xr-storage/
  xrd-3:
    cap_add:
    - CHOWN
    - DAC_OVERRIDE
    - FSETID
    - FOWNER
    - MKNOD
    - NET_RAW
    - SETGID
    - SETUID
    - SETFCAP
    - SETPCAP
    - NET_BIND_SERVICE
    - SYS_CHROOT
    - KILL
    - AUDIT_WRITE
    - SYS_NICE
    - SYS_ADMIN
    - SYS_RESOURCE
    - NET_ADMIN
    - SYS_PTRACE
    - IPC_LOCK
    cap_drop:
    - all
    container_name: xrd-3
    devices:
    - /dev/fuse
    - /dev/net/tun
    environment:
      XR_EVERY_BOOT_CONFIG: /etc/xrd/startup.cfg
      XR_INTERFACES: linux:xr-40,xr_name=Gi0/0/0/0;linux:xr-50,xr_name=Gi0/0/0/1;linux:xr-00,xr_name=Gi0/0/0/2;linux:xr-80,xr_name=Gi0/0/0/3
      XR_MGMT_INTERFACES: linux:xr-120,xr_name=Mg0/RP0/CPU0/0,chksum
    image: ios-xr/xrd-control-plane:25.1.1
    networks:
      mgmt: null
      xrd-1-gi0-xrd-3-gi2: null
      xrd-3-gi0-xrd-4-gi0: null
      xrd-3-gi1-xrd-5-gi1: null
      xrd-3-gi3-xrd-7-gi0: null
    pids_limit: -1
    security_opt:
    - apparmor=unconfined
    - label=disable
    stdin_open: true
    tty: true
    volumes:
    - source: ./xrd-3-startup.cfg
      target: /etc/xrd/startup.cfg
      type: bind
    - xrd-3:/xr-storage/
  xrd-4:
    cap_add:
    - CHOWN
    - DAC_OVERRIDE
    - FSETID
    - FOWNER
    - MKNOD
    - NET_RAW
    - SETGID
    - SETUID
    - SETFCAP
    - SETPCAP
    - NET_BIND_SERVICE
    - SYS_CHROOT
    - KILL
    - AUDIT_WRITE
    - SYS_NICE
    - SYS_ADMIN
    - SYS_RESOURCE
    - NET_ADMIN
    - SYS_PTRACE
    - IPC_LOCK
    cap_drop:
    - all
    container_name: xrd-4
    devices:
    - /dev/fuse
    - /dev/net/tun
    environment:
      XR_EVERY_BOOT_CONFIG: /etc/xrd/startup.cfg
      XR_INTERFACES: linux:xr-40,xr_name=Gi0/0/0/0;linux:xr-60,xr_name=Gi0/0/0/1;linux:xr-20,xr_name=Gi0/0/0/2;linux:xr-90,xr_name=Gi0/0/0/3
      XR_MGMT_INTERFACES: linux:xr-120,xr_name=Mg0/RP0/CPU0/0,chksum
    image: ios-xr/xrd-control-plane:25.1.1
    networks:
      mgmt: null
      xrd-2-gi0-xrd-4-gi2: null
      xrd-3-gi0-xrd-4-gi0: null
      xrd-4-gi1-xrd-6-gi1: null
      xrd-4-gi3-xrd-7-gi1: null
    pids_limit: -1
    security_opt:
    - apparmor=unconfined
    - label=disable
    stdin_open: true
    tty: true
    volumes:
    - source: ./xrd-4-startup.cfg
      target: /etc/xrd/startup.cfg
      type: bind
    - xrd-4:/xr-storage/
  xrd-5:
    cap_add:
    - CHOWN
    - DAC_OVERRIDE
    - FSETID
    - FOWNER
    - MKNOD
    - NET_RAW
    - SETGID
    - SETUID
    - SETFCAP
    - SETPCAP
    - NET_BIND_SERVICE
    - SYS_CHROOT
    - KILL
    - AUDIT_WRITE
    - SYS_NICE
    - SYS_ADMIN
    - SYS_RESOURCE
    - NET_ADMIN
    - SYS_PTRACE
    - IPC_LOCK
    cap_drop:
    - all
    container_name: xrd-5
    devices:
    - /dev/fuse
    - /dev/net/tun
    environment:
      XR_EVERY_BOOT_CONFIG: /etc/xrd/startup.cfg
      XR_INTERFACES: linux:xr-70,xr_name=Gi0/0/0/0;linux:xr-50,xr_name=Gi0/0/0/1;linux:xr-10,xr_name=Gi0/0/0/2;linux:xr-100,xr_name=Gi0/0/0/3
      XR_MGMT_INTERFACES: linux:xr-120,xr_name=Mg0/RP0/CPU0/0,chksum
    image: ios-xr/xrd-control-plane:25.1.1
    networks:
      mgmt: null
      xrd-1-gi1-xrd-5-gi2: null
      xrd-3-gi1-xrd-5-gi1: null
      xrd-5-gi0-xrd-6-gi0: null
      xrd-5-gi3-xrd-8-gi0: null
    pids_limit: -1
    security_opt:
    - apparmor=unconfined
    - label=disable
    stdin_open: true
    tty: true
    volumes:
    - source: ./xrd-5-startup.cfg
      target: /etc/xrd/startup.cfg
      type: bind
    - xrd-5:/xr-storage/
  xrd-6:
    cap_add:
    - CHOWN
    - DAC_OVERRIDE
    - FSETID
    - FOWNER
    - MKNOD
    - NET_RAW
    - SETGID
    - SETUID
    - SETFCAP
    - SETPCAP
    - NET_BIND_SERVICE
    - SYS_CHROOT
    - KILL
    - AUDIT_WRITE
    - SYS_NICE
    - SYS_ADMIN
    - SYS_RESOURCE
    - NET_ADMIN
    - SYS_PTRACE
    - IPC_LOCK
    cap_drop:
    - all
    container_name: xrd-6
    devices:
    - /dev/fuse
    - /dev/net/tun
    environment:
      XR_EVERY_BOOT_CONFIG: /etc/xrd/startup.cfg
      XR_INTERFACES: linux:xr-70,xr_name=Gi0/0/0/0;linux:xr-60,xr_name=Gi0/0/0/1;linux:xr-30,xr_name=Gi0/0/0/2;linux:xr-110,xr_name=Gi0/0/0/3
      XR_MGMT_INTERFACES: linux:xr-120,xr_name=Mg0/RP0/CPU0/0,chksum
    image: ios-xr/xrd-control-plane:25.1.1
    networks:
      mgmt: null
      xrd-2-gi1-xrd-6-gi2: null
      xrd-4-gi1-xrd-6-gi1: null
      xrd-5-gi0-xrd-6-gi0: null
      xrd-6-gi3-xrd-8-gi1: null
    pids_limit: -1
    security_opt:
    - apparmor=unconfined
    - label=disable
    stdin_open: true
    tty: true
    volumes:
    - source: ./xrd-6-startup.cfg
      target: /etc/xrd/startup.cfg
      type: bind
    - xrd-6:/xr-storage/
  xrd-7:
    cap_add:
    - CHOWN
    - DAC_OVERRIDE
    - FSETID
    - FOWNER
    - MKNOD
    - NET_RAW
    - SETGID
    - SETUID
    - SETFCAP
    - SETPCAP
    - NET_BIND_SERVICE
    - SYS_CHROOT
    - KILL
    - AUDIT_WRITE
    - SYS_NICE
    - SYS_ADMIN
    - SYS_RESOURCE
    - NET_ADMIN
    - SYS_PTRACE
    - IPC_LOCK
    cap_drop:
    - all
    container_name: xrd-7
    devices:
    - /dev/fuse
    - /dev/net/tun
    environment:
      XR_EVERY_BOOT_CONFIG: /etc/xrd/startup.cfg
      XR_INTERFACES: linux:xr-80,xr_name=Gi0/0/0/0;linux:xr-90,xr_name=Gi0/0/0/1
      XR_MGMT_INTERFACES: linux:xr-120,xr_name=Mg0/RP0/CPU0/0,chksum
    image: ios-xr/xrd-control-plane:25.1.1
    networks:
      mgmt: null
      xrd-3-gi3-xrd-7-gi0: null
      xrd-4-gi3-xrd-7-gi1: null
    pids_limit: -1
    security_opt:
    - apparmor=unconfined
    - label=disable
    stdin_open: true
    tty: true
    volumes:
    - source: ./xrd-7-startup.cfg
      target: /etc/xrd/startup.cfg
      type: bind
    - xrd-7:/xr-storage/
  xrd-8:
    cap_add:
    - CHOWN
    - DAC_OVERRIDE
    - FSETID
    - FOWNER
    - MKNOD
    - NET_RAW
    - SETGID
    - SETUID
    - SETFCAP
    - SETPCAP
    - NET_BIND_SERVICE
    - SYS_CHROOT
    - KILL
    - AUDIT_WRITE
    - SYS_NICE
    - SYS_ADMIN
    - SYS_RESOURCE
    - NET_ADMIN
    - SYS_PTRACE
    - IPC_LOCK
    cap_drop:
    - all
    container_name: xrd-8
    devices:
    - /dev/fuse
    - /dev/net/tun
    environment:
      XR_EVERY_BOOT_CONFIG: /etc/xrd/startup.cfg
      XR_INTERFACES: linux:xr-100,xr_name=Gi0/0/0/0;linux:xr-110,xr_name=Gi0/0/0/1
      XR_MGMT_INTERFACES: linux:xr-120,xr_name=Mg0/RP0/CPU0/0,chksum
    image: ios-xr/xrd-control-plane:25.1.1
    networks:
      mgmt: null
      xrd-5-gi3-xrd-8-gi0: null
      xrd-6-gi3-xrd-8-gi1: null
    pids_limit: -1
    security_opt:
    - apparmor=unconfined
    - label=disable
    stdin_open: true
    tty: true
    volumes:
    - source: ./xrd-8-startup.cfg
      target: /etc/xrd/startup.cfg
      type: bind
    - xrd-8:/xr-storage/
version: '2.4'
volumes:
  xrd-1:
    name: xrd-1
  xrd-2:
    name: xrd-2
  xrd-3:
    name: xrd-3
  xrd-4:
    name: xrd-4
  xrd-5:
    name: xrd-5
  xrd-6:
    name: xrd-6
  xrd-7:
    name: xrd-7
  xrd-8:
    name: xrd-8
